### model
model_name_or_path: google/gemma-3-270m
trust_remote_code: true
resize_vocab: true
add_special_tokens: "<|im_start|>,<|im_end|>,<|user|>,<|assistant|>"

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: rnnandi/bn-turn-detection-dataset-train-v3-refined-50k
template: qwen_turn
default_system: ""
cutoff_len: 512
# max_samples: 1000  # Remove limit to use full dataset
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: models/qwen2_5-1_5b-bn-turn-detector-full
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: turn_detector_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

